# Form implementation generated from reading ui file 'AltitudeDisplay.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AltitudeDisplay(object):
    def setupUi(self, AltitudeDisplay):
        AltitudeDisplay.setObjectName("AltitudeDisplay")
        AltitudeDisplay.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        AltitudeDisplay.resize(616, 784)
        self.gridLayout_2 = QtWidgets.QGridLayout(AltitudeDisplay)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_11 = QtWidgets.QGroupBox(AltitudeDisplay)
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.altitude_SB_2 = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.altitude_SB_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(120)
        font.setBold(False)
        self.altitude_SB_2.setFont(font)
        self.altitude_SB_2.setStyleSheet("")
        self.altitude_SB_2.setFrame(False)
        self.altitude_SB_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.altitude_SB_2.setReadOnly(True)
        self.altitude_SB_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.altitude_SB_2.setDecimals(1)
        self.altitude_SB_2.setMinimum(-100.0)
        self.altitude_SB_2.setMaximum(1000.0)
        self.altitude_SB_2.setObjectName("altitude_SB_2")
        self.gridLayout_10.addWidget(self.altitude_SB_2, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(60)
        font.setBold(False)
        font.setItalic(False)
        self.label_16.setFont(font)
        self.label_16.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_16.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_16.setScaledContents(False)
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 0, 0, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_11, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(AltitudeDisplay)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_plotC = QtWidgets.QGridLayout()
        self.gridLayout_plotC.setObjectName("gridLayout_plotC")
        self.gridLayout.addLayout(self.gridLayout_plotC, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_2.setRowStretch(1, 1)

        self.retranslateUi(AltitudeDisplay)
        QtCore.QMetaObject.connectSlotsByName(AltitudeDisplay)

    def retranslateUi(self, AltitudeDisplay):
        _translate = QtCore.QCoreApplication.translate
        AltitudeDisplay.setWindowTitle(_translate("AltitudeDisplay", "Altitude Display"))
        self.altitude_SB_2.setSuffix(_translate("AltitudeDisplay", " m"))
        self.label_16.setText(_translate("AltitudeDisplay", "Altitude"))
        self.groupBox.setTitle(_translate("AltitudeDisplay", "Graph Zone"))
